 
name: ADRdemo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.4
  - pandas
  - numpy
  - pip
  - tensorflow==1.14.0
  - pip:
    - opencv-python
    - streamlit
    - whl/tflite_runtime-1.14.0-cp37-cp37m-linux_x86_64.whl
